#!/bin/bash

CPU="$1$2"
if [ "$2" == "v7le" ]; then
  CPUDIR="$1le-v7"
  BUSUFFIX="$1v7"
elif [ "$2" == "a9" ]; then
  CPUDIR="$1le-v7"
  CPU="$1v7le"
  BUSUFFIX="$1v7"
  CPUGEN="a9"
else
  CPUDIR="$CPU"
  BUSUFFIX="$1"
fi

if [ ! -z "$USE_ICECC" -a "$USE_ICECC" = "Yes" ] ; then
    CC_COMMAND=`which icecc`
    echo "Using icecream for distributed compiling"
else
    CC_COMMAND=$QNX_HOST/usr/bin/qcc
fi

if [ -z "$BUILDTYPE" ] ; then
    BUILDTYPE="Release"
fi

if [ ! -z "$PROFILE" ] ; then
    PROFILER_FLAGS="-p"
else
    PROFILER_FLAGS=""
fi

STAGE_LIB="$STAGE_DIR/$CPUDIR/lib"
STAGE_USR_LIB="$STAGE_DIR/$CPUDIR/usr/lib"
STAGE_INC="$STAGE_DIR/usr/include"

QNX_INCLUDE="$QNX_TARGET/usr/include"
QNX_USR_LIB="$QNX_TARGET/$CPUDIR/usr/lib"
QNX_LIB="$QNX_TARGET/$CPUDIR/lib"

COMP_PATHS=" \
    -Wl,-rpath-link,$QNX_LIB \
    -Wl,-rpath-link,$QNX_USR_LIB \
    -L$QNX_LIB \
    -L$QNX_USR_LIB \
    -I$QNX_INCLUDE"

if [ "$CCWRAP" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DCMAKE_C_COMPILER_ARG1=qcc \
        -DCMAKE_CXX_COMPILER_ARG1=qcc"
    CC_COMMAND="$CCWRAP"
fi

if [ "`uname`" == "Darwin" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DCMAKE_SKIP_RPATH='ON' \
        $CMAKE_EXTRA_OPTIONS"
fi

if [ "$ENABLE_DRT" == "1" ] ; then
    CMAKE_EXTRA_OPTIONS=" \
        -DENABLE_DRT=1 \
        $CMAKE_EXTRA_OPTIONS"
fi

if [[ "`uname`" == *MINGW32* ]] ; then
    CC_COMMAND="$CC_COMMAND.exe"
fi
if [[ "$OS" == *Windows* ]] ; then
    CC_COMMAND="$CC_COMMAND.exe"
    echo cmake \
        -DCMAKE_SYSTEM_PROCESSOR="$CPUDIR" \
        -DCMAKE_SYSTEM_NAME="QNX" \
        -DCMAKE_SYSTEM_VERSION="1" \
        -DCMAKE_BUILD_TYPE="$BUILDTYPE" \
        -DCMAKE_C_COMPILER="$CC_COMMAND" \
        -DCMAKE_CXX_COMPILER="$CC_COMMAND" \
        -DCMAKE_C_FLAGS="-Vgcc_nto$CPU -g $COMP_PATHS $PROFILER_FLAGS" \
        -DCMAKE_CXX_FLAGS="-Vgcc_nto${CPU}_cpp-ne -g -lang-c++ $COMP_PATHS $PROFILER_FLAGS" \
        -DCMAKE_AR="$QNX_HOST/usr/bin/nto$BUSUFFIX-ar" \
        -DCMAKE_RANLIB="$QNX_HOST/usr/bin/nto$BUSUFFIX-ranlib" \
        -DCMAKE_LINKER="$QNX_HOST/usr/bin/nto$BUSUFFIX-ld" \
        -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=TRUE \
        -G\"Eclipse CDT4 - Unix Makefiles\" \
        $CMAKE_EXTRA_OPTIONS \
        $3 ../native > cmd.bat
    cmd //c cmd.bat
    rm cmd.bat
else
    cmake \
        -DCMAKE_SYSTEM_PROCESSOR="$CPUDIR" \
        -DCMAKE_SYSTEM_NAME="QNX" \
        -DCMAKE_SYSTEM_VERSION="1" \
        -DCMAKE_BUILD_TYPE="$BUILDTYPE" \
        -DCMAKE_C_COMPILER="$CC_COMMAND" \
        -DCMAKE_CXX_COMPILER="$CC_COMMAND" \
        -DCMAKE_C_FLAGS="-Vgcc_nto$CPU -g $COMP_PATHS $PROFILER_FLAGS" \
        -DCMAKE_CXX_FLAGS="-Vgcc_nto${CPU}_cpp-ne -g -lang-c++ $COMP_PATHS $PROFILER_FLAGS" \
        -DCMAKE_AR="$QNX_HOST/usr/bin/nto$BUSUFFIX-ar" \
        -DCMAKE_RANLIB="$QNX_HOST/usr/bin/nto$BUSUFFIX-ranlib" \
        -DCMAKE_LINKER="$QNX_HOST/usr/bin/nto$BUSUFFIX-ld" \
        -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=TRUE \
        -G"Eclipse CDT4 - Unix Makefiles" \
        $CMAKE_EXTRA_OPTIONS \
        $3 ../native
fi
